const cityNameEntries = [
  ['Amsterdam', '阿姆斯特丹'],
  ['Antwerp', '安特卫普'],
  ['Athens', '雅典'],
  ['Auckland', '奥克兰'],
  ['Austin', '奥斯汀'],
  ['Abidjan', '阿比让'],
  ['Abu Dhabi', '阿布扎比'],
  ['Accra', '阿克拉'],
  ['Addis Ababa', '亚的斯亚贝巴'],
  ['Adelaide', '阿德莱德'],
  ['Ahmedabad', '艾哈迈达巴德'],
  ['Algiers', '阿尔及尔'],
  ['Amman', '安曼'],
  ['Asuncion', '亚松森'],
  ['Bangalore', '班加罗尔'],
  ['Bengaluru', '班加罗尔'],
  ['Bangkok', '曼谷'],
  ['Barcelona', '巴塞罗那'],
  ['Baghdad', '巴格达'],
  ['Baltimore', '巴尔的摩'],
  ['Bandung', '万隆'],
  ['Basel', '巴塞尔'],
  ['Beirut', '贝鲁特'],
  ['Belo Horizonte', '贝洛奥里藏特'],
  ['Beijing', '北京'],
  ['Berlin', '柏林'],
  ['Birmingham', '伯明翰'],
  ['Bogota', '波哥大'],
  ['Bogotá', '波哥大'],
  ['Bonn', '波恩'],
  ['Boston', '波士顿'],
  ['Brasília', '巴西利亚'],
  ['Brasilia', '巴西利亚'],
  ['Bratislava', '布拉迪斯拉发'],
  ['Brisbane', '布里斯班'],
  ['Brussels', '布鲁塞尔'],
  ['Bucharest', '布加勒斯特'],
  ['Budapest', '布达佩斯'],
  ['Buenos Aires', '布宜诺斯艾利斯'],
  ['Busan', '釜山'],
  ['Cairo', '开罗'],
  ['Calgary', '卡尔加里'],
  ['Cali', '卡利'],
  ['Campinas', '坎皮纳斯'],
  ['Canberra', '堪培拉'],
  ['Can Tho', '芹苴'],
  ['Caracas', '加拉加斯'],
  ['Cape Town', '开普敦'],
  ['Casablanca', '卡萨布兰卡'],
  ['Cebu', '宿务'],
  ['Chengdu', '成都'],
  ['Chennai', '金奈'],
  ['Chicago', '芝加哥'],
  ['Chongqing', '重庆'],
  ['Christchurch', '基督城'],
  ['Charlotte', '夏洛特'],
  ['Cleveland', '克利夫兰'],
  ['Colombo', '科伦坡'],
  ['Cologne', '科隆'],
  ['Copenhagen', '哥本哈根'],
  ['Cordoba', '科尔多瓦'],
  ['Córdoba', '科尔多瓦'],
  ['Curitiba', '库里蒂巴'],
  ['Dallas', '达拉斯'],
  ['Da Nang', '岘港'],
  ['Daejeon', '大田'],
  ['Daegu', '大邱'],
  ['Dakar', '达喀尔'],
  ['Damascus', '大马士革'],
  ['Dar es Salaam', '达累斯萨拉姆'],
  ['Delhi', '德里'],
  ['Denver', '丹佛'],
  ['Dhaka', '达卡'],
  ['Doha', '多哈'],
  ['Dubai', '迪拜'],
  ['Dublin', '都柏林'],
  ['Durban', '德班'],
  ['Düsseldorf', '杜塞尔多夫'],
  ['Dusseldorf', '杜塞尔多夫'],
  ['Eindhoven', '埃因霍温'],
  ['Edinburgh', '爱丁堡'],
  ['Edmonton', '埃德蒙顿'],
  ['Essen', '埃森'],
  ['Eygelshoven', '艾赫尔斯霍芬'],
  ['Florence', '佛罗伦萨'],
  ['Fortaleza', '福塔莱萨'],
  ['Fukuoka', '福冈'],
  ['Frankfurt', '法兰克福'],
  ['Frankfurt am Main', '法兰克福'],
  ['Geneva', '日内瓦'],
  ['Ghent', '根特'],
  ['Glasgow', '格拉斯哥'],
  ['Gold Coast', '黄金海岸'],
  ['Gothenburg', '哥德堡'],
  ['Gdansk', '格但斯克'],
  ['Gdańsk', '格但斯克'],
  ['Guadalajara', '瓜达拉哈拉'],
  ['Guayaquil', '瓜亚基尔'],
  ['Gwangju', '光州'],
  ['Guangzhou', '广州'],
  ['Hamburg', '汉堡'],
  ['Hangzhou', '杭州'],
  ['Hanoi', '河内'],
  ['Harare', '哈拉雷'],
  ['Helsinki', '赫尔辛基'],
  ['Ho Chi Minh City', '胡志明市'],
  ['Hong Kong', '香港'],
  ['Houston', '休斯敦'],
  ['Hyderabad', '海得拉巴'],
  ['Incheon', '仁川'],
  ['Islamabad', '伊斯兰堡'],
  ['Isfahan', '伊斯法罕'],
  ['Istanbul', '伊斯坦布尔'],
  ['Jakarta', '雅加达'],
  ['Jaipur', '斋浦尔'],
  ['Jeddah', '吉达'],
  ['Johor Bahru', '新山'],
  ['Johannesburg', '约翰内斯堡'],
  ['Kansas City', '堪萨斯城'],
  ['Kampala', '坎帕拉'],
  ['Karachi', '卡拉奇'],
  ['Kathmandu', '加德满都'],
  ['Kaohsiung', '高雄'],
  ['Kazan', '喀山'],
  ['Kigali', '基加利'],
  ['Kiev', '基辅'],
  ['Kyiv', '基辅'],
  ['Kyoto', '京都'],
  ['Kolkata', '加尔各答'],
  ['Kuala Lumpur', '吉隆坡'],
  ['Kuwait City', '科威特城'],
  ['Krakow', '克拉科夫'],
  ['Kraków', '克拉科夫'],
  ['Lagos', '拉各斯'],
  ['La Paz', '拉巴斯'],
  ['Lausanne', '洛桑'],
  ['Las Vegas', '拉斯维加斯'],
  ['Leeds', '利兹'],
  ['Lahore', '拉合尔'],
  ['Lima', '利马'],
  ['Lisbon', '里斯本'],
  ['Liverpool', '利物浦'],
  ['Lille', '里尔'],
  ['Liege', '列日'],
  ['Liège', '列日'],
  ['London', '伦敦'],
  ['Los Angeles', '洛杉矶'],
  ['Lyon', '里昂'],
  ['Lodz', '罗兹'],
  ['Łódź', '罗兹'],
  ['Luanda', '罗安达'],
  ['Lusaka', '卢萨卡'],
  ['Madrid', '马德里'],
  ['Makassar', '望加锡'],
  ['Manila', '马尼拉'],
  ['Manchester', '曼彻斯特'],
  ['Manama', '麦纳麦'],
  ['Mandalay', '曼德勒'],
  ['Manaus', '马瑙斯'],
  ['Marseille', '马赛'],
  ['Maputo', '马普托'],
  ['Malmö', '马尔默'],
  ['Malmo', '马尔默'],
  ['Melbourne', '墨尔本'],
  ['Mecca', '麦加'],
  ['Medan', '棉兰'],
  ['Medellin', '麦德林'],
  ['Medellín', '麦德林'],
  ['Medina', '麦地那'],
  ['Mexico City', '墨西哥城'],
  ['Miami', '迈阿密'],
  ['Milan', '米兰'],
  ['Minneapolis', '明尼阿波利斯'],
  ['Monterrey', '蒙特雷'],
  ['Montevideo', '蒙得维的亚'],
  ['Montréal', '蒙特利尔'],
  ['Montreal', '蒙特利尔'],
  ['Moscow', '莫斯科'],
  ['Mumbai', '孟买'],
  ['Munich', '慕尼黑'],
  ['Muscat', '马斯喀特'],
  ['Nairobi', '内罗毕'],
  ['Nagoya', '名古屋'],
  ['Naples', '那不勒斯'],
  ['Nantes', '南特'],
  ['Nashville', '纳什维尔'],
  ['Nanjing', '南京'],
  ['New Delhi', '新德里'],
  ['New York', '纽约'],
  ['New York City', '纽约'],
  ['Nice', '尼斯'],
  ['North Bergen', '北卑尔根'],
  ['Novosibirsk', '新西伯利亚'],
  ['Nuremberg', '纽伦堡'],
  ['Osaka', '大阪'],
  ['Oslo', '奥斯陆'],
  ['Orlando', '奥兰多'],
  ['Ottawa', '渥太华'],
  ['Paris', '巴黎'],
  ['Penang', '槟城'],
  ['Perth', '珀斯'],
  ['Philadelphia', '费城'],
  ['Phnom Penh', '金边'],
  ['Phoenix', '菲尼克斯'],
  ['Pittsburgh', '匹兹堡'],
  ['Prague', '布拉格'],
  ['Portland', '波特兰'],
  ['Porto', '波尔图'],
  ['Porto Alegre', '阿雷格里港'],
  ['Pretoria', '比勒陀利亚'],
  ['Pune', '浦那'],
  ['Quebec City', '魁北克城'],
  ['Quito', '基多'],
  ['Rio de Janeiro', '里约热内卢'],
  ['Riyadh', '利雅得'],
  ['Rabat', '拉巴特'],
  ['Rawalpindi', '拉瓦尔品第'],
  ['Raleigh', '罗利'],
  ['Recife', '累西腓'],
  ['Reykjavik', '雷克雅未克'],
  ['Riga', '里加'],
  ['Rome', '罗马'],
  ['Rosario', '罗萨里奥'],
  ['Rostov-on-Don', '顿河畔罗斯托夫'],
  ['Rotterdam', '鹿特丹'],
  ['Sacramento', '萨克拉门托'],
  ['Salt Lake City', '盐湖城'],
  ['Salvador', '萨尔瓦多'],
  ['Samara', '萨马拉'],
  ['Saint Petersburg', '圣彼得堡'],
  ['San Francisco', '旧金山'],
  ['San Diego', '圣迭戈'],
  ['San Jose', '圣何塞'],
  ['Santiago', '圣地亚哥'],
  ['Sarajevo', '萨拉热窝'],
  ['Sapporo', '札幌'],
  ['Seville', '塞维利亚'],
  ['Sharjah', '沙迦'],
  ['São Paulo', '圣保罗'],
  ['Sao Paulo', '圣保罗'],
  ['Seattle', '西雅图'],
  ['Seoul', '首尔'],
  ['Shanghai', '上海'],
  ['Shenzhen', '深圳'],
  ['Singapore', '新加坡'],
  ['Skopje', '斯科普里'],
  ['Sofia', '索非亚'],
  ['St. Louis', '圣路易斯'],
  ['St Louis', '圣路易斯'],
  ['Stockholm', '斯德哥尔摩'],
  ['Stuttgart', '斯图加特'],
  ['Surabaya', '泗水'],
  ['Surat', '苏拉特'],
  ['Sydney', '悉尼'],
  ['Taipei', '台北'],
  ['Taichung', '台中'],
  ['Tainan', '台南'],
  ['Tallinn', '塔林'],
  ['Tampa', '坦帕'],
  ['Tel Aviv', '特拉维夫'],
  ['Tehran', '德黑兰'],
  ['The Hague', '海牙'],
  ['Thessaloniki', '塞萨洛尼基'],
  ['Tirana', '地拉那'],
  ['Tokyo', '东京'],
  ['Toronto', '多伦多'],
  ['Toulouse', '图卢兹'],
  ['Tunis', '突尼斯'],
  ['Turin', '都灵'],
  ['Utrecht', '乌得勒支'],
  ['Valencia', '瓦伦西亚'],
  ['Vancouver', '温哥华'],
  ['Venice', '威尼斯'],
  ['Vientiane', '万象'],
  ['Vienna', '维也纳'],
  ['Vilnius', '维尔纽斯'],
  ['Warsaw', '华沙'],
  ['Washington', '华盛顿'],
  ['Washington D.C.', '华盛顿'],
  ['Wellington', '惠灵顿'],
  ['Winnipeg', '温尼伯'],
  ['Wroclaw', '弗罗茨瓦夫'],
  ['Wrocław', '弗罗茨瓦夫'],
  ['Wuhan', '武汉'],
  ['Yangon', '仰光'],
  ['Yekaterinburg', '叶卡捷琳堡'],
  ['Yokohama', '横滨'],
  ['Xi’an', '西安'],
  ["Xi'an", '西安'],
  ['Xian', '西安'],
  ['Anshan', '鞍山'],
  ['Baoding', '保定'],
  ['Changchun', '长春'],
  ['Changsha', '长沙'],
  ['Changzhou', '常州'],
  ['Dali', '大理'],
  ['Dalian', '大连'],
  ['Deyang', '德阳'],
  ['Dongguan', '东莞'],
  ['Foshan', '佛山'],
  ['Fuzhou', '福州'],
  ['Guilin', '桂林'],
  ['Guiyang', '贵阳'],
  ['Haikou', '海口'],
  ['Harbin', '哈尔滨'],
  ['Hefei', '合肥'],
  ['Hengyang', '衡阳'],
  ['Hohhot', '呼和浩特'],
  ['Huai’an', '淮安'],
  ["Huai'an", '淮安'],
  ['Huaian', '淮安'],
  ['Huainan', '淮南'],
  ['Huizhou', '惠州'],
  ['Anqing', '安庆'],
  ['Anyang', '安阳'],
  ['Anshun', '安顺'],
  ['Baise', '百色'],
  ['Baoji', '宝鸡'],
  ['Baotou', '包头'],
  ['Bengbu', '蚌埠'],
  ['Benxi', '本溪'],
  ['Binzhou', '滨州'],
  ['Cangzhou', '沧州'],
  ['Changde', '常德'],
  ['Chaozhou', '潮州'],
  ['Chengde', '承德'],
  ['Chenzhou', '郴州'],
  ['Chifeng', '赤峰'],
  ['Chuzhou', '滁州'],
  ['Daqing', '大庆'],
  ['Dandong', '丹东'],
  ['Danzhou', '儋州'],
  ['Dazhou', '达州'],
  ['Dongying', '东营'],
  ['Ordos', '鄂尔多斯'],
  ['Fangchenggang', '防城港'],
  ['Fushun', '抚顺'],
  ['Fuyang', '阜阳'],
  ['Guangyuan', '广元'],
  ['Golmud', '格尔木'],
  ['Heze', '菏泽'],
  ['Hengshui', '衡水'],
  ['Huaihua', '怀化'],
  ['Huangshi', '黄石'],
  ['Huludao', '葫芦岛'],
  ['Huzhou', '湖州'],
  ['Jiaxing', '嘉兴'],
  ['Jiamusi', '佳木斯'],
  ['Jiangmen', '江门'],
  ['Jiaozuo', '焦作'],
  ['Jiayuguan', '嘉峪关'],
  ['Jingdezhen', '景德镇'],
  ['Jingmen', '荆门'],
  ['Jingzhou', '荆州'],
  ['Jilin', '吉林'],
  ['Jining', '济宁'],
  ['Jinhua', '金华'],
  ['Jinzhou', '锦州'],
  ['Jiujiang', '九江'],
  ['Jiuquan', '酒泉'],
  ['Kaifeng', '开封'],
  ['Karamay', '克拉玛依'],
  ['Kashgar', '喀什'],
  ['Korla', '库尔勒'],
  ['Lanzhou', '兰州'],
  ['Langfang', '廊坊'],
  ['Leshan', '乐山'],
  ['Lianyungang', '连云港'],
  ['Lincang', '临沧'],
  ['Liaocheng', '聊城'],
  ['Lishui', '丽水'],
  ['Lhasa', '拉萨'],
  ['Linyi', '临沂'],
  ['Liuzhou', '柳州'],
  ['Liupanshui', '六盘水'],
  ['Luoyang', '洛阳'],
  ['Luzhou', '泸州'],
  ['Maanshan', '马鞍山'],
  ['Maoming', '茂名'],
  ['Meishan', '眉山'],
  ['Meizhou', '梅州'],
  ['Mianyang', '绵阳'],
  ['Mudanjiang', '牡丹江'],
  ['Nanchang', '南昌'],
  ['Nanchong', '南充'],
  ['Nanning', '南宁'],
  ['Nantong', '南通'],
  ['Nanyang', '南阳'],
  ['Neijiang', '内江'],
  ['Ningbo', '宁波'],
  ['Panjin', '盘锦'],
  ['Panzhihua', '攀枝花'],
  ['Pingdingshan', '平顶山'],
  ['Putian', '莆田'],
  ['Qinhuangdao', '秦皇岛'],
  ['Qingyuan', '清远'],
  ['Qinzhou', '钦州'],
  ['Qingdao', '青岛'],
  ['Qiqihar', '齐齐哈尔'],
  ['Quanzhou', '泉州'],
  ['Qujing', '曲靖'],
  ['Quzhou', '衢州'],
  ['Rizhao', '日照'],
  ['Sanya', '三亚'],
  ['Shantou', '汕头'],
  ['Shangqiu', '商丘'],
  ['Shangrao', '上饶'],
  ['Shaoxing', '绍兴'],
  ['Shaoguan', '韶关'],
  ['Shaoyang', '邵阳'],
  ['Shenyang', '沈阳'],
  ['Shijiazhuang', '石家庄'],
  ['Shiyan', '十堰'],
  ['Suqian', '宿迁'],
  ['Suining', '遂宁'],
  ['Suzhou', '苏州'],
  ['Taian', '泰安'],
  ["Tai'an", '泰安'],
  ['Taiyuan', '太原'],
  ['Taizhou', '台州'],
  ['Tangshan', '唐山'],
  ['Tongliao', '通辽'],
  ['Tongren', '铜仁'],
  ['Tianjin', '天津'],
  ['Urumqi', '乌鲁木齐'],
  ['Weihai', '威海'],
  ['Weifang', '潍坊'],
  ['Weinan', '渭南'],
  ['Wenzhou', '温州'],
  ['Wuxi', '无锡'],
  ['Wuzhou', '梧州'],
  ['Xiamen', '厦门'],
  ['Xianning', '咸宁'],
  ['Xiangtan', '湘潭'],
  ['Xianyang', '咸阳'],
  ['Xining', '西宁'],
  ['Xiangyang', '襄阳'],
  ['Xingtai', '邢台'],
  ['Xinyang', '信阳'],
  ['Xinxiang', '新乡'],
  ['Xinyu', '新余'],
  ['Xuchang', '许昌'],
  ['Xuzhou', '徐州'],
  ['Yaan', '雅安'],
  ["Ya'an", '雅安'],
  ['Yanan', '延安'],
  ["Yan'an", '延安'],
  ['Yancheng', '盐城'],
  ['Yangzhou', '扬州'],
  ['Yantai', '烟台'],
  ['Yibin', '宜宾'],
  ['Yichang', '宜昌'],
  ['Yichun', '宜春'],
  ['Yinchuan', '银川'],
  ['Yining', '伊宁'],
  ['Yiyang', '益阳'],
  ['Yongzhou', '永州'],
  ['Yueyang', '岳阳'],
  ['Yulin', '玉林'],
  ['Zaozhuang', '枣庄'],
  ['Zhangjiakou', '张家口'],
  ['Zhangye', '张掖'],
  ['Zhangzhou', '漳州'],
  ['Zhanjiang', '湛江'],
  ['Zhaoqing', '肇庆'],
  ['Zhenjiang', '镇江'],
  ['Zhengzhou', '郑州'],
  ['Zhongshan', '中山'],
  ['Zhoukou', '周口'],
  ['Zhoushan', '舟山'],
  ['Zhuhai', '珠海'],
  ['Zhuzhou', '株洲'],
  ['Zhumadian', '驻马店'],
  ['Zigong', '自贡'],
  ['Zunyi', '遵义'],
  ['Zurich', '苏黎世'],
] as const

export const countryNameZhMap: Record<string, string> = {
  China: '中国',
  'United States': '美国',
  'The Netherlands': '荷兰',
  Netherlands: '荷兰',
  Russia: '俄罗斯',
  Germany: '德国',
  Brazil: '巴西',
  India: '印度',
  Singapore: '新加坡',
  Vietnam: '越南',
  France: '法国',
  'United Kingdom': '英国',
  Japan: '日本',
  'South Korea': '韩国',
  Australia: '澳大利亚',
  Taiwan: '中国台湾',
  Thailand: '泰国',
  Indonesia: '印度尼西亚',
  Malaysia: '马来西亚',
  Philippines: '菲律宾',
  'United Arab Emirates': '阿联酋',
  Turkey: '土耳其',
  Israel: '以色列',
  'Saudi Arabia': '沙特阿拉伯',
  Pakistan: '巴基斯坦',
  Bangladesh: '孟加拉国',
  Canada: '加拿大',
  Mexico: '墨西哥',
  Panama: '巴拿马',
  'Costa Rica': '哥斯达黎加',
  Argentina: '阿根廷',
  Chile: '智利',
  Colombia: '哥伦比亚',
  Peru: '秘鲁',
  Venezuela: '委内瑞拉',
  Uruguay: '乌拉圭',
  Ecuador: '厄瓜多尔',
  Bolivia: '玻利维亚',
  'South Africa': '南非',
  Egypt: '埃及',
  Nigeria: '尼日利亚',
  Kenya: '肯尼亚',
  Morocco: '摩洛哥',
  Tunisia: '突尼斯',
  Ghana: '加纳',
  Ethiopia: '埃塞俄比亚',
  Tanzania: '坦桑尼亚',
  Algeria: '阿尔及利亚',
  Senegal: '塞内加尔',
  'Ivory Coast': '科特迪瓦',
  Spain: '西班牙',
  Italy: '意大利',
  Sweden: '瑞典',
  Norway: '挪威',
  Finland: '芬兰',
  Poland: '波兰',
  'Czech Republic': '捷克',
  Austria: '奥地利',
  Switzerland: '瑞士',
  Ukraine: '乌克兰',
  Romania: '罗马尼亚',
  Ireland: '爱尔兰',
  Belgium: '比利时',
  Denmark: '丹麦',
  Portugal: '葡萄牙',
  Greece: '希腊',
  Unknown: '未知',
}

function normalizeCityName(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[’‘`]/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
    .toLocaleLowerCase('en-US')
}

export const cityNameZhMap: Record<string, string> = Object.fromEntries(cityNameEntries)

const normalizedCityNameZhMap = new Map(
  cityNameEntries.map(([name, translated]) => [normalizeCityName(name), translated]),
)

export function getCityNameZh(value?: string | null): string | null {
  const city = value?.trim()
  if (!city) return null
  if (/[\u3400-\u9fff]/u.test(city)) return city
  return normalizedCityNameZhMap.get(normalizeCityName(city)) ?? null
}

export function displayCityName(value?: string | null): string {
  const city = value?.trim()
  if (!city || normalizeCityName(city) === 'unknown') return '未知'
  return getCityNameZh(city) ?? city
}

export function displayCountryName(value?: string | null): string {
  const country = value?.trim()
  if (!country) return '未知'
  return countryNameZhMap[country] ?? country
}
